name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: <YOUR_AWS_REGION>

    - name: Build and push Docker image
      id: build-image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: <YOUR_AWS_ACCOUNT_ID>.dkr.ecr.<YOUR_AWS_REGION>.amazonaws.com/<YOUR_REPOSITORY_NAME>:latest

    - name: Deploy to Amazon ECS
      id: deploy-ecs
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: <TASK_DEFINITION_PATH>
        service: <YOUR_ECS_SERVICE_NAME>
        cluster: <YOUR_ECS_CLUSTER_NAME>
        wait-for-service-stability: true
